# Generated by Django 5.1.3 on 2025-02-11 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cine',
            name='actor',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Actor',
        ),
    ]
